Added api and cmd
esemi/psychic-couscous pull request #19
Opened 2021-09-30 17:35 UTC by METALmasterKS

2021-09-30 17:41 UTC, esemi commented
proto of #15

2021-09-30 17:44 UTC, esemi requested changes

2021-09-30 17:44 UTC, esemi commented on cmd/app/internal/controller/movie.go
> +func (c *movieController) CreateMovie(ctx echo.Context) (err error) {
а почему create на роутере GET /api/v1/movies ?

2021-09-30 18:57 UTC, METALmasterKS commented on cmd/app/internal/controller/movie.go
> +func (c *movieController) CreateMovie(ctx echo.Context) (err error) {
поменял на _health

2021-10-01 22:01 UTC, esemi approved these changes

2022-01-07 17:18 UTC, closed without merging